BNode* build_graph() {
BNode * n0 = (BNode *) malloc(sizeof(BNode));
BNode * n1 = (BNode *) malloc(sizeof(BNode));
BNode * n2 = (BNode *) malloc(sizeof(BNode));
BNode * n3 = (BNode *) malloc(sizeof(BNode));
BNode * n4 = (BNode *) malloc(sizeof(BNode));
BNode * n5 = (BNode *) malloc(sizeof(BNode));
BNode * n6 = (BNode *) malloc(sizeof(BNode));
BNode * n7 = (BNode *) malloc(sizeof(BNode));
BNode * n8 = (BNode *) malloc(sizeof(BNode));
n2->next = n4;
n1->next = n5;
n5->next = n6;
n0->next = n7;
n4->next = n8;
n6->next = n0;
n3->next = n1;
n7->next = n2;
n8->next = n3;
n8->value = 4;
n4->value = 10;
n7->value = 10;
n0->value = 15;
n3->value = 2;
n2->value = 11;
n6->value = 11;
n1->value = 1;
n5->value = 0;
return n0;
}